version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run:
          name: Test
          command: npm run test
          environment:
            MOCHA_FILE: /home/circleci/test-results/test-results.[hash].xml
            MOCHA_REPORTER: mocha-junit-reporter
            when: always
      - store_test_results:
          path: /home/circleci/test-results
      - store_artifacts:
          path: /home/circleci/test-results

workflows:
  build_and_test:
    jobs:
      - build-and-test
