version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.18.0
      - image: postgres:15.8-alpine
        name: pg-pix-bot
        environment:
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    resource_class: small
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run:
          name: Test
          command: npm run test
          environment:
            TEST_DATABASE_API_URL: postgres://circleci@pg-pix-bot:5432/circleci
            MOCHA_FILE: /home/circleci/test-results/test-results.[hash].xml
            MOCHA_REPORTER: mocha-junit-reporter
            when: always
      - store_test_results:
          path: /home/circleci/test-results
      - store_artifacts:
          path: /home/circleci/test-results

workflows:
  build_and_test:
    jobs:
      - build-and-test
