version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build-and-test
